apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacion
  namespace: ejemplo-k8s
spec:
  selector:
    matchLabels:
      app: aplicacion
  replicas: 3
  template:
    metadata:
      labels:
        app: aplicacion
    spec:
      containers:
        - name: aplicacion
          imagePullPolicy: Always
          image: 'php:7.4-apache'
          ports:
            - containerPort: 80
          volumeMounts:
            - name: codigo-fuente
              mountPath: /var/www/html
      volumes: 
        - name: codigo-fuente
          hostPath: 
            path: /Users/gonzalo.martinez/ejemplito-k8s/
            type: DirectoryOrCreate

          