apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ejemplo-k8s
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          imagePullPolicy: Always
          image: 'mysql:8'
          env: 
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: "basesita"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: base-de-datos
              mountPath: /var/lib/mysql


