apiVersion: v1
kind: Service
metadata:
  name: aplicacion
  namespace: ejemplo-k8s
spec:
  selector:
    app: aplicacion
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ejemplo-k8s
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30306
    